### ISSUE TITLE
Short Hand jssStyleSheet not overwriting some defaults

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1015]
Repro:

1. implement `<TextField/>` component
2. apply jssStyleSheet that shorthands the border property `border: "2px dashed red"`
3. observe `<TextField/>` component the border width and styles are applied but not the color

**Comment by nicholasrice** [comment]
Closing this issue and opening a new one on text-field.

The JSSManager is working as expected. The reason `border: "2px dashed red" ` does not apply a border color is because the `border-color` property is applied separately in the text-field stylesheet and *after* the `border` property is applied. This means the `border-color` property will override `border`.

To fix this particular issue, text-field should define it's border using a single `border` property instead of a `border` *and* `border-color` property
