### ISSUE TITLE
Keyboard enter does not fire on click on contentMenuItem

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1195]
**Describe the bug**
Keyboard enter does not fire on click on `<contentMenuItem/>`.

**To Reproduce**
1. Implement an `onClick()` on `<contentMenuItem/>`
2. Focus `<contentMenuItem/>` with keyboard
3. Hit `Enter` on keyboard

**Expected behavior**
`Enter` on keyboard should fire `onClick()`

**Comment by chrisdholt** [comment]
@nicholasrice do you mind if I take this?

**Comment by chrisdholt** [comment]
@nicholasrice and I synced up on this and originally found that the best likely path forward would be to update this to either be an HTML button element, or extend our button component to support both anchors and buttons long term. This would allow unhandledProps to continue handling onClick and onKeyDown events for the context menu item.

When attempting to implement this, I ran across a bug where button elements in chrome cannot be grid (or flex) containers (https://github.com/rachelandrew/gridbugs#10-some-html-elements-cant-be-grid-containers). This bug is blocked by requiring the implementation of a new layout engine.

With that in mind, we'll add new callbacks for onKeyDown and onClick to expose the event callbacks for the current implementation using `<div>`
