### ISSUE TITLE
Odd "undefined" attributes sometimes added to components 

### ISSUE THREAD

**Issue by scomea** [microsoft/fast-dna#1397]
1. Launch the fast documentation app for MSFT React components
2. Go to "Action toggle"
3. Inspect the dom (see attached screenshot)
4. Note the odd undefined="[object object]" attribute on the action toggle

You can see similar results on other components that use render props (listbox item, action trigger). 

We should not be writing nonsense to the dom.  JaneChu thinks there are issues related to our handling of unhandled props that is causeing this.

![image](https://user-images.githubusercontent.com/7649425/53050609-985f8100-344e-11e9-8516-2e1cc701481a.png)

**Comment by chrisdholt** [comment]
Thanks @scomea - I'll investigate this

**Comment by chrisdholt** [comment]
+ @janechu 

After an initial investigation, I've found that this really only repro's within the context of our dev/explore site. Outside of that context, no additional undefined attributes are being added. From my initial trace though I can confirm that it has something to do with how we're managing the render prop data in the examples file; likely somewhere within the context of the plugin architecture. 

I wasn't able to trace *exactly* where the issue was being initiated from, but my hunch is that it's somehow related to `mapDataToComponent` or where/how it's being applied. After inspecting the objects in the DOM, they appear to have the same shape as those in `mapDataToComponent`:

```
if (!childOption) {
    value = Object.assign(
        { id: subSchemaId },
        React.createElement(
            React.Fragment,
            { key: `${subSchemaId}-${index}` },
            subDataNormalized
        )
   );
} else {
    value = Object.assign(
        { id: subSchemaId },
        React.createElement(childOption.component, {
            key: `${subSchemaId}-${index}`,
             ...subDataNormalized,
        })
    );
}
```

It appears that in the object being passed, we are spreading it onto the root of the components.

Below is a screenshot to illustrate that when stripped out from the dev site, this issues is not repro'ing.
<img width="1086" alt="action toggle in non dev environment" src="https://user-images.githubusercontent.com/13071055/53108867-a06dfe00-34ec-11e9-90be-dafbff271bdc.png">

**Comment by chrisdholt** [comment]
Talking with @janechu we tracked this to the plugins in MSFT package. Will take this and get it fixed

**Comment by chrisdholt** [comment]
React children are sometimes undefined when plugins are overriding them. This appears to happen when there are two children - one which is a string and one which is a child option. Reassigning back to @janechu
