### ISSUE TITLE
CSSRules interface does not extend CSS.Properties correctly

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/fast-dna#1489]
Cannot pass numerical value to zIndex because CSSRules interface does not extend CSS.Properties correctly.

I have the following example.
```typescript
export const styles: ComponentStyles<CssClasses, DesignSystem> =() =>{
  return {
   footer: {
     zIndex: 10 
   }
  }
}
```
TypeScript is throwing a waring that the type of zIndex has to be string. 

The cause is a type mismatch:
```typescript
export interface CSSRules<T> {
    [rule: string]: CSSRules<T> | CSSRuleResolver<T> | CSSStaticRule;
}

export declare type CSSStaticRule = CSS.Properties | string;
```
The type CSSStaticRule assigns the CSS Properties object type to each rule meaning that
```typescript
export const styles: ComponentStyles<CssClasses, DesignSystem> =() =>{
  return {
   footer: {
     anything: {
      zIndex: 10
    }
   }
  }
}
```
is valid; however
```typescript
export const styles: ComponentStyles<CssClasses, DesignSystem> =() =>{
  return {
   footer: {
     zIndex: 10 
   }
  }
}
```
is invalid.

JSS does not recognize the key `anything`, so the `zIndex` is not set in the page.

The following code changes will fix this problem.
```typescript
export type CssRules<T> = CSSComputedRules<T> | CSS.Properties;
export interface CSSComputedRules<T> {
    [rule: string]: CSSComputedRules<T> | CSSRuleResolver<T> | string;
}
```

**Comment by nicholasrice** [comment]
Thanks @shaohaolin-

I integrated your proposed changes but it caused numerous errors. Part of the problem, I believe, is that `CSSComputedRules` would also need to contain `CSS.Properties` (otherwise values could only be a function, string, or object - not a number). Adding that fixed some of the issues (and fixes the TS error in the invalid fixture you reference) but existing stylesheets fail to compile with the change. I will look into this further but wanted to post an update.

**Comment by shaohaolin** [comment]
@nicholasrice  Any update for this?
