### ISSUE TITLE
Add "onBlur" and "onFocus" to handled props for TextAction

### ISSUE THREAD

**Issue by camsmithmicrosoft** [Microsoft/fast-dna#1645]
**What feature are you requesting?**

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by camsmithmicrosoft** [comment]
The element that takes unhandled props for TextAction is a div, not the underlying input which makes onFocus and onBlur as unhandled props useless

**Comment by chrisdholt** [comment]
Thanks @camsmithmicrosoft - Interesting enough, this is the *one* case where we pass unhandled props to the input and not the div. We have not appropriately documented this and we have an outstanding issue tracking this as we understand that the above statement (unhandled passed to the div as expected behavior) creates the issue you pointed out. However, the problem you're likely running into is that we are using the onBlur and onFocus events but not providing an opportunity for a callback to be passed.

I think that's a big miss on our part and we'll add those explicitly to ensure that users can manage blur and focus appropriately.
