### ISSUE TITLE
Update a11y for Toggle component

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#173]
### Expected behavior 
Raise the bar to grade C accessibility
### Actual behavior
Evaluate current behavior and make updates to reach expected behavior

**Comment by Wilto** [comment]
Based on some [prototyping](https://codepen.io/Wilto/pen/ZoGoQm), I’ve come back around to advocating for checkboxes instead of the ARIA 1.1 `button[aria-pressed]` pattern. `button[aria-pressed]` _works_, but JAWS needs a redundant `aria-checked` to effectively communicate the state. That redundant state gets read aloud by NVDA, giving us the following narration:

**NVDA:** 
> “SUBSCRIBE TO THE THING. SUBSCRIBED. PRESSED, **CHECKED**.” ->
“SUBSCRIBE TO THE THING. NOT SUBSCRIBED. NOT PRESSED, **NOT CHECKED.**”
  
**VoiceOver:** 
> “ON, SUBSCRIBE TO THE THING, SWITCH. SUBSCRIBED.” ->
“OFF, SUBSCRIBE TO THE THING, SWITCH. NOT SUBSCRIBED.”
  
**JAWS:**
> “SUBSCRIBE TO THE THING, PRESS, ON.” ->
“SUBSCRIBE TO THE THING, PRESS, OFF.”
  
**Narrator:**
> “ON. SUBSCRIBE TO THE THING, BUTTON. SUBSCRIBED.” ->
“OFF. SUBSCRIBE TO THE THING, BUTTON. NOT SUBSCRIBED.”

This pattern isn’t completely untenable; it still _works_. But between this and a hidden input to capture the form value to be submitted, it leaves us owning a lot more of the interaction than a native checkbox would.

**Comment by chrisdholt** [comment]
Doing a scrub on toggle, so reassigning to self

**Comment by chrisdholt** [comment]
closed by #838
