### ISSUE TITLE
custom test names in snapshot generation

### ISSUE THREAD

**Issue by prabashn** [microsoft/fast-dna#1750]
**Describe the bug; what happened?**
Nick added support for custom test descriptions with this bugfix: https://github.com/microsoft/fast-dna/issues/582

However when attempting to use this feature, there are TS intellisense errors due to this feature not being properly accounted in the typescript types.

**What are the steps to reproduce the issue?**

Example:

Implement a snapshot test (see screenshot) with the custom test description.

**What behavior did you expect?**
No intellisense errors

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/40579735/57638312-64ce5780-7562-11e9-85e2-ad065aca64f3.png)

**In what environment did you see the issue?**
N/A - development

**Is there any additional context?**
https://github.com/microsoft/fast-dna/issues/582

**Comment by chrisdholt** [comment]
@prabashn I don't think this is a bug, I think the typing error here is correct and expected. It looks like you are using the same data for examples with a dev site instance as well as the snapshots. While I believe that worked at one time due to "duck typing", the feature added by #582 is specific to snapshots, so the typing for the ComponentFactoryExample<T> is throwing an error. Since the feature isn't supported or part of the ComponentFactoryExample<T> contract, I think this is actually a valid delta.

Setting the typing to `SnapshotTestSuite<T>` would likely show this as supported.

**Comment by prabashn** [comment]
Ah, you're absolutely correct, Chris. Thank you! Closing.

**Comment by prabashn** [comment]
![image](https://user-images.githubusercontent.com/40579735/57639563-06ef3f00-7565-11e9-80da-14c3318d4faa.png)
