### ISSUE TITLE
Dialog is not scrollable when zoomed in

### ISSUE THREAD

**Issue by adkaufm** [microsoft/fast-dna#1871]
When you zoom in so that some elements inside the dialog are cut off, no scroll bar appears to access those elements.

Repro:
1. Go to Dialog in the component explorer.
2. Add multiple elements to the dialog. I added images because they stack vertically.
3. Zoom in the browser to 400%, or just enough where some of the images are cut off.
4. Observe - a scrollbar seems to appear, but it doesn't scroll in the dialog to see the elements that are cut off.

I expect a scroll bar would appear so you can scroll around in the dialog and still see all the elements when zoomed in.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/44783604/59638967-a7a9bf00-910e-11e9-8aff-f17da19a3b0b.png)
![image](https://user-images.githubusercontent.com/44783604/59639025-d758c700-910e-11e9-88e1-a7fa6ca09231.png)

**Comment by chrisdholt** [comment]
@adkaufm @nicholasrice I wonder if this is something we actually want to manage in this basic dialog markup which takes children. I’m concerned that we may be making an assumption about the content and expected reflow. Could this be solved just as easily by passing a "wrapped" content region into the dialog that passes those styles (inline for simplicity)? 

```
<Dialog {...props}>
   <div style={{overflow: 'auto'}}>
         <Heading />
         <Image />
         <Image />
         <Image />
   </div>
</Dialog>
```

What if I want a fixed heading but the content below it scrollable?
```
<Dialog {...props}>
   <Heading />
   <div style={{overflow: 'auto'}}>
         <Image />
         <Image />
         <Image />
   </div>
</Dialog>
```

I could be missing the issue here though; perhaps there’s something else going on?

**Comment by chrisdholt** [comment]
After further thought, I think this is related to something else going on. I think this has to do with positioning. With content in the dialog, even when the inner content region passed has a scrollable region, the dialog pushes outside the bounds of the viewport.

**Comment by nalogiudice** [comment]
A solution is to add `overflow:auto` to the `dialog_positioningRegion`. This allows the "body" to overflow when needed, but allows the developer to dictate the inner scroll behavior of the dialog.

This style can either be part of the FAST JSS or could be passed by the developer.

**Comment by chrisdholt** [comment]
@nalogiudice would adding a maxheight and maxwidth for 100vh and 100vw respectively help this situation?

**Comment by nalogiudice** [comment]
@chrisdholt this ^ does not seem to be a viable solution after testing.

**Comment by chrisdholt** [comment]
Can you elaborate on why? I’m seeing the top of the dialog well above the top of the viewport; does setting overflow fix that issue as well?

**Comment by nalogiudice** [comment]
> Can you elaborate on why?

Adding those styles to any of the applicable regions does not fix the overflow issue. Maybe I am missing something though, but I did try adding these styles to any region that made sense and it did not solve this issue.

> I’m seeing the top of the dialog well above the top of the viewport; does setting overflow fix that issue as well?

I'm not sure I understand what you are seeing/ I am unable to repo? I am following the exact steps above to repo. Can you provide more information?

Regardless, why is adding `overflow: "auto"` to `dialog_positioningRegion` not a valid solution?

**Comment by chrisdholt** [comment]
Thanks @nalogiudice. I think my primary concern is if we *have to* add overflow to the positioning region to get this to work. It may well be required. When I added content to the dialog as @adkaufm points out above and then zoom in to 400%, the top of the dialog is actually forced above the top of the browser window. I’m wondering if the primary underlying issue here is related to that problem. From what I can tell, the overflow of the content itself should be handled within the dialog (per the comment above), but I’m wondering if there is a way to manage the height and width of the dialog so it’s constrained to the window.

**Comment by eljefe223** [comment]
The problem is that `dialog_positioningRegion` class has the following properties:

```
display: "flex",
alignItems: "center",
```

Aligning the items center causes the center the `dialog` class to be centered within the screen and as you zoom if the height of the `dialog` is greater than the screen area the top becomes clipped.

The solution is to remove `alignItems: "center"` from `dialog_positioningRegion` and add `marginTop: "auto", marginBottom: "auto" to the `dialog` class and add `overflow: "auto"` to the `dialog_positioningRegion` class. This allows the dialog to always be centered vertically until the height of the dialog is greater than the available space which then aligns the top of the dialog with the top of the browser window.

I've created a codePen that illustrates the problem zoom in on both:
Broken:
https://codepen.io/eljefe223/pen/yLBOxOe

Solution:
https://codepen.io/eljefe223/pen/aboNjyd

**Comment by chrisdholt** [comment]
Looks like the solution needs to be updated, but I was able to test with the suggestion you made above. Looks good - can you send a PR for the changes to the positioning region?
