### ISSUE TITLE
Progress: Add "paused" or "disabled" state

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#2192]
Often progress bars can be used as part of file upload or download controls. While the progress element doesn't have the concept of being "disabled" or "paused" we should likely have this concept within the MSFT version of the control. Semantics are at play here as the control itself is technically not disabled. If we can land the semantics, this implementation is fairly simple.

**Comment by janechu** [comment]
I like "paused", other potential wording could be:
- suspended
- delayed

I think whichever word is used, it should be able to be used in conjuncture with "resumed", but any of those three are fine with me.

**Comment by khamudom** [comment]
When I think of "disabled", it's usually on an action type item. Progress to me is like an indicator of an action happening. 
The 3 options Jane suggested all work. I too am leaning towards "paused".

**Comment by bheston** [comment]
I think "paused" works best as well. I've been meaning to write up this feature too.

**Comment by chrisdholt** [comment]
@bheston what recipe would you recommend tying the "paused" state to?

**Comment by bheston** [comment]
@chrisdholt, @eljefe223, Great question. I've been noticing there's a need for a stronger selection color like this, but based on the current recipes let's use `neutralForegroundHint`. It has more contrast against the base neutral fill and coordinates with the accent fill in normal state.

While we're here, we need to update the running state to use accentForegroundRest instead of the fill. In dark mode there is not enough contrast for the relatively small size of the progress component compared to something like a button.

![Progress](https://user-images.githubusercontent.com/47367562/63963706-6f95f500-ca4a-11e9-8a6a-79bc811ce79f.png)

**Comment by bheston** [comment]
Updated with full fill for indeterminate paused state.

![image](https://user-images.githubusercontent.com/47367562/63967587-98ba8380-ca52-11e9-9439-f677fe438a6b.png)
