### ISSUE TITLE
Color changes made to layers of a component in Figma are not retained when an instance is created.

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [microsoft/fast-dna#2598]
**Description**
When using the plugin on a component master in Figma, changes are made successfully. However, when you copy the master to create an instance, the only chnages that remain intact that were made via the plugin are at the root/parent layer of the instance. Any nested layers lose the styling.

**Steps to reproduce the issue:**

1. Create a component master of a button
2. Apply color definitions via the plugin
3. Create a copy (instance) of the master component
4. Observe that the metadata in the plugin of those layers is lost.

**Expected behavior**
Metadata changes made via the plugin are not lost

**Comment by nicholasrice** [comment]
It was communicated to me by Figma's support team that this behavior is intended - plugin data stored on a component does not reflect to component instances on instantiation. 

We'll need to come up with an alternative solution. One option that comes to mind is offering UX to copy plugin data from component -> instance when an instance node is selected. When clicked, the plugin would assign plugin data to the instance from the master.

It's not ideal, but since there is no mechanism to subscribe to instance creation, we're forced to wait for user input to do that work.

**Comment by Jeremy-Knudsen** [comment]
We've filed a bug on Figma and they let us know it is a known issue and have no plans to fix it. Thus, closing and we'll design a workaround for this issue.
