### ISSUE TITLE
Proposal: remove Picturefill dependency

### ISSUE THREAD

**Issue by Wilto** [Microsoft/fast-dna#263]
We’re still [referencing Picturefill as a dependency in the wiki](https://github.com/Microsoft/fast-dna/wiki); should it officially be dropped? Support for [`picture`](https://caniuse.com/#search=picture) and [`srcset`](https://caniuse.com/#search=sizes) is pretty robust these days, and the native fallback pattern for both (`img[src]`) is solid. 

Ultimately, it would mean IE11 getting the fallback `src` instead of native respimg behavior, as a default—but, no reason an author couldn’t drop in Picturefill if that would be a sticking point on their project(s).

cc @eljefe223

**Comment by chrisdholt** [comment]
I think this is a valid request, and I'm not sure we need to include this in our bundle, but it's worth a discussion. Anyone who relies on > IE11 as part of their browser matrix would need to add it themselves. 

I do think that this would be much more noticeable - for instance, now that we are mobile first instead of IE8 first, the src within picture defaults to VP1. In the case of layouts with large responsive images, that would be pretty noticeable.

All that said, I think we should consider documenting this as a necessary dependency for people who need to support > IE11. I don't know that we need to provide the dependency though as a package ourselves.

**Comment by Wilto** [comment]
> I do think that this would be much more noticeable - for instance, now that we are mobile first instead of IE8 first, the src within picture defaults to VP1. In the case of layouts with large responsive images, that would be pretty noticeable.

Yeah, for sure—if we did drop it, I’d probably advocate for changing the fallback `src`to the largest source. It would look the same, all told; it wouldn’t be as over-the-wire performant in IE11, but you’d lose the render-time overhead of the polyfill. With `srcset`/`sizes`, that change is pretty painless. 

Where the inner `img` is considered the “unqualified” source for `picture`, we’d have to use `max-width` in `source[media]` for that approach. It _works_ just fine, but it isn’t as common (or expected) as `min-width`.

**Comment by chrisdholt** [comment]
@Wilto can you setup a meeting for next week sometime where we can walk through the pros/cons of this all up?

**Comment by Wilto** [comment]
Absolutely; invitations going out shortly.

**Comment by chrisdholt** [comment]
Per conversations today -

We will not include Picturefill in our bundle, but we will document that it is needed for browsers that do not natively support the picture element.

**Comment by chrisdholt** [comment]
created #277 to track. Closing in favor of that task.
