### ISSUE TITLE
[Proposal] Change Foundation Element Registration

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast-dna#3348]
## Problem

There are a growing number of things that are starting to bother me with our components:

* We cannot have more than one design system on a page at a time
* We don't have a way to let customers disambiguate element names if needed
* We have an awkward need to have seemingly inert expressions just to prevent tree shaking
* Our design systems add an additional layer of inheritance just to associate styles
  * And we end up with multiple classes with similar names in our API docs
* There is not a good "timing" to allow customers to specify a custom element registry (when that platform feature becomes available)

## Proposed Solution

To address all these issues, I recommend the following:

* Remove our inherited classes and decorator usage in both `fast-components` and `fast-components-msft`
* Introduce a new `createElementRegistration` helper function in `fast-foundation`, to be used by the design system
* Define our elements imperatively in each of the design system packages using the new `createElementRegistration` function
* Ask customers to import the registration function and call it for each components they want to use
* Provide an `allComponents` aggregate function for convenience
* Have the single file script builds import and call the `allComponents` function
* The explicit registration process now gives us a place to enable future registration options such as custom registries

## Code Examples

Let's get a bit more concrete with some code.

### fast-element

At present, `fast-element` already provides an imperative method for defining elements. The API looks something like this:

```ts
class FASTElement extends HTMLElement {
    static define(type: Function, definition: any) {}
}
```

The `define` static function allow you to pass a class and a definition object. Internally it does all the registration with the platform, as well as a number of other one-time optimizations for the component. The definition object is the same shape as what is passed to the `customElement` decorator.

So, no changes are needed in `fast-element`.

### fast-foundation

To `fast-foundation` we add an interface and a helper function for creating registrations. This is a non-breaking addition to the package.

```ts
interface ElementRegistrationOptions {
  name?: string;
  template?: ElementViewTemplate;
  styles?: ElementStyles;
}

const registeredTypes = new Set();

function createElementRegistration(ElementType: Function, defaultOptions: Required<ElementRegistrationOptions>) {
    return function(options?: ElementRegistrationOptions) {
      if (registeredTypes.has(ElementType)) {
        ElementType = class extends ElementType {};
      }

      registeredTypes.add(ElementType);

      const finalDef = Object.assign({}, defaultOptions, options);
      return FASTElement.define(ElementType, finalDef);
    }
}
```

This function can be used to create a registration function that will capture a design system's default configuration, but also allow the end user to override various details. Additionally, if the component type has already been registered, it will create a new subclass so that the platform can effectively allow multiple versions of the same component under different names.

### fast-components (and fast-components-msft)

In our design system packages, we should remove the subclassing and decorator usage. Instead we'll use the registration function above. Here's what that would look like for Anchor.

```ts
export const anchor = createElementRegistration(Anchor, {
  name: 'fast-anchor',
  template: AnchorTemplate,
  styles: FASTAnchorStyles
});
```

Additionally, we'll add an `allComponents` helper as follows:

```ts
export function allComponents() {
  designSystemProvider();
  anchor();
  ...
}
```

This helper will be used in the single file script build as follows:

```ts
import { allComponents } from './index';

allComponents();
```

### Customer Code

Customers now have less odd looking code to write when using a components:

```ts
import { designSystemProvider, anchor } from '@microsoft/fast-components';

designSystemProvider();
anchor();
```

Additionally, they can now do something like this:

```ts
import { designSystemProvider, anchor, button } from '@microsoft/fast-components';
import { designSystemProvider as dspMSFT, anchor as anchorMSFT } from '@microsoft/fast-components-msft';

// register default fast components
designSystemProvider();
anchor();

// change the default anatomy
button({ template: customButtonTemplate });

// also bring in the msft versions and disambiguate
dspMSFT({ name: 'msft-design-system-provider' });
anchorMSFT({ name: 'msft-anchor' });

// in the future, specify a custom registry
button({ registry: myElementRegistry });
```

## Outliers

If I recall, the `badge` is one case where there's an extra attribute in one of the design system versions. To handle this, I'd recommend that we move the attribute to the base version. It's a tiny bit of code and is harmless. The design system can use it or not without consequence. If that is not acceptable, the registration function above could be adjusted to enable also providing a set of additional attrs and prototype members to add. I'd like to avoid that if possible though. I think that we should strive to have a a consistent API for the component in code, regardless of the design system.

## Level of Effort

This is not a difficult change. Almost all of the code is listed above. It's mostly a tedious boilerplate update to `fast-components` and `fast-compnents-msft`. It can be done pretty quickly. We'd need to make a minor update to our docs as well and let anyone know who is using these components. Note that I think this will make our API docs cleaner. There won't be multiple class definitions anymore (e.g. Anchor and FASTAnchor).

**Comment by chrisdholt** [comment]
I think some of this is due to decisions that were previously made, which certainly can all be changed - I do want to point out a few things to clarify at the start:

> - We cannot have more than one design system on a page at a time

I don't think this is entirely accurate. You're using the term design system, but I think you mean that you cannot host two different sets of components at a time. You can support two different design systems at the same time on the page. You cannot have two different design-system-providers between fast-components and fast-components-msft on the page at the same time because of registration issues. Design systems absolutely should support inheritance, and technically, I can merge them in my own DSP implementation. I don't think that's what's being discussed here. If I'm building a site using the MSFT design system I should be able to extend that provider to support my own custom attributes and properties as well.

When we were implementing #3088 I had proposed having different namespaces in order to ensure that there were two different registered elements which could be used on the same page. The concern here was that it would require more work from implementors to change tag names - though, I think registration again was the problem here. There was also a concern that it would appear that we don't have "one" set of components, which I don't actually think is an issue.

The naming issue with registration is currently a unique problem to us because we host multiple design systems in our repository. If I were to create the MSFT design system in my role on the product side, I certainly would not prefix my anchor or button with FAST. Similarly, if Lightning or Material, or Apple, or IBM were to leverage FAST element to implement their own components, I wouldn't think they would register it as a FAST component.

Similarly, I think the interface thing is uniquely a problem for us because we are hosting two component libraries and technically two design systems. Were these in different projects similar to the prefixing issue above, would the duplicate API problem still be an issue?

> Our design systems add an additional layer of inheritance just to associate styles
> And we end up with multiple classes with similar names in our API docs

I don't agree with the assumption that inheritance only serves to associate styles. I can think of many areas where inheritance makes sense. In FAST we've had the concept of "base components", which ultimately serve as primitives. They are the foundational bit of code, most often associated with an existing HTML element (form controls) or W3C standard widgets. As you look across design systems, there are patterns which are created by companies and organizations for convenience, which are semantically named and often exported as first-class components for convenience. More on this below, but I do want to note that I'll be addressing the outliers section as well:

> If I recall, the badge is one case where there's an extra attribute in one of the design system versions. To handle this, I'd recommend that we move the attribute to the base version. It's a tiny bit of code and is harmless. The design system can use it or not without consequence. If that is not acceptable, the registration function above could be adjusted to enable also providing a set of additional attrs and prototype members to add. I'd like to avoid that if possible though. I think that we should strive to have a a consistent API for the component in code, regardless of the design system.

As an implementor of a design system library, I want to be able to create many of the patterns mentioned above as web components. Many times the control I want to build associates with an existing component and pattern but requires some additional attributes or I want to export it as a first-class citizen so it can be reused easily across the organization.

A few concrete examples below which pertain directly to MSFT - these are not exhaustive, there are several more I could likely list off the top of my head:
- **Call to action**: Call to action is an anchor/button, but not all anchors/buttons are call to actions. The call to action at MSFT traditionally includes a `>` which may include a micro interaction and is a pattern used across microsoft.com. To build this I would likely extend the anchor or button and include that SVG in the after slot. Now I have a reusable pattern that the ENG teams at MSFT can use quickly without having to repeat the pattern.  *Note: Even as we look to align via open-ui, certain things will differ across design systems, and I think that's okay. Appearance attributes will differ across systems - I do not think we'll get design *teams* to agree to a universal standard for appearance naming. I'd go so far as to say that appearance should not be included in the base component, but should be able to be added after the fact at the "design system" level (fast-components, fast-components-msft). Technically, our appearances only align because we haven't done a super deep dive into our FAST design system.*
- **Color swatch**: This is an example we leverage in our docs site, and I know there are examples across several MSFT properties of this as well. The color swatch in many of the cases I've seen functions as a radio. Some teams have different visuals here as well or they may want an attr/propery for background color so they can programatically set it and update it dynamically. From a foundational standpoint, this is an extension of another component, but it is *distinctly* a part of a given design system.
- **Badge**: To address the badge note above, we've already hoisted certain properties which may not actually span across design systems. The MSFT badge is vastly different than Material, Salesforce, etc. 

I could be misreading here, but I think we're wading back into the concept of "one thing to rule them all", and I think that's fundamentally a bad decision. I previously expressed this, but I think it's a bad idea at the design system level and I think it's a bad idea at the component level. I am *all for* adding better ergonomics for registration and leveraging components from different packages at the same time. I am all for solving and simplifying some of the registration issues above. As it currently stands, I don't support the current proposal above because I think there are some flawed assumptions and I fundamentally disagree with hoisting unique scenarios from various design systems to a single API. The foundational button should be basic; if someone wants to overload their instance of a button because they value that convenience they should be able to do so with inheritance. I should not have to inherit their requirements for the sake of that convenience.

**Comment by chrisdholt** [comment]
Quick note; you mentioned the following in Discord:
> They don't have to hoist to the base. If we allow the registration to pass in attributes, it can simply apply them to the prototype.

It would be helpful for me to see the above proposal with the above taken as a requirement. If we adopt that as the pattern/rule for inheritance then I think most of my concerns go away. I do think the naming issue is still uniquely ours, but that's not a sticking issue for me. My primary concern is that we have a model for extending what we consider our "base" components.

**Comment by EisenbergEffect** [comment]
@chrisdholt Sorry to alarm you! I should have spent some more time working out the details before posting this. As I've been continuing to review things over the last weeks, I just had a growing realization that we might have a few issues we need to address.

I'll follow up with a more detailed explanation later or an alternate proposal (there are some other things I'm also thinking of that aren't detailed here that should probably be explained as well), but I just wanted to note that nothing I'm proposing or would propose would prevent the ability to inherit from base classes or extends via adding new properties. I'm also not trying to solve the problem of "one thing to rule them all".

**Comment by EisenbergEffect** [comment]
Closing this issue in favor of a more wholistic proposal: https://github.com/microsoft/fast-dna/issues/3361
