### ISSUE TITLE
Discussion: A package for JSS style editing needs a name

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#598]
We are creating a package for a JSS style editor that will be a collection of React components, following our current convention I suggest the package name be fast-jss-editor-react.

Further details on the contents and purpose of the package can be found in task #597

**Comment by chrisdholt** [comment]
I'm good with this package name for the most part. From a previous conversation, it seemed like this could be used outside of jss, but I think specifying to jss is helpful and it aligns with our overall philosophy. The word "editor" still throws me off a bit, perhaps because it seems like it could be two different things, but I can't really articulate a better option

**Comment by nicholasrice** [comment]
I take it this will be a lot like the schema form generator, except for specific to CSS properties, is that correct?

To continue off of @chrisdholt's thread - could this be applied outside of JSS? Is this more specific to CSS than JSS?

**Comment by nalogiudice** [comment]
Would the user care that it is JSS vs CSS? If not, then I say go with the name `style`. And is it more of a `configurator` than an `editor`?

**Comment by janechu** [comment]
@nicholasrice somewhat correct, the form would not be generated because there is no given schema that someone would be supplying to create it like with the form generator. They would just use the components they wanted to achieve the style manipulation they are looking for.

I think we could say CSS instead of JSS and I agree it could be called configurator, that is essentially what it is.

How do people feel about `fast-css-configurator-react`.

**Comment by nalogiudice** [comment]
I'm fine with it. You prefer `css` over the more generic `style`?

**Comment by janechu** [comment]
I prefer it because its specific, it configures CSS values.

**Comment by nalogiudice** [comment]
Sounds good to me.

**Comment by awentzel** [comment]
I prefer `fast-styles-configurator-react`.  It's very likely that the configurator will require performance tuning and in this case I would want to support whatever direction style goes CSS or JSS.

**Comment by janechu** [comment]
@awentzel what it is ultimately doing is configuring CSS, mappings to property names may come from JSS or any other place to say something like `background-image` property in CSS maps to `backgroundImage` in JSS or maybe it maps to another name for another system but ultimately what it will feed back are CSS values.

'Styles' could be for any system styles and we have no plans to make a package that deals with style systems across platforms so it would be too broad a scope.

**Comment by janechu** [comment]
@nicholasrice @awentzel last call on the name, we have +2 from @chrisdholt and @nalogiudice  for `fast-css-configurator-react`.

**Comment by awentzel** [comment]
+1 for `fast-styles-configurator-react` since you argued my main point.  What we are "doing" is styling  "mappings to property names may come from JSS or any other place"  To me, it's about what the user gets?  The user gets the ability to style a configurator.  The means is CSS.  The end result is Styles.  If we name too specifically or based on technology we don't leave room for technology changes over time.

**Comment by chrisdholt** [comment]
One of the reasons I like `css` in this case is that it it's a commonly used word when dealing with styling on the web and it's specific. @awentzel - I'm wondering if using the word "styles" as you proposed actually causes more confusion due to our current naming conventions. Does this only configure fast-styles? In my mind, binding it to the technology makes it more clear that this is a tool that allows a user to accelerate using a specific technology. `fast-styles-configurator-react` seems to infer to me that it is specifically intended for use with fast-styles things.

**Comment by Falkicon** [comment]
Based on the patterns I am seeing for our existing projects we use [fast]-[tech]-[role]-[framework]. If we agree this is the pattern, I propose we name this one "fast-css-editor-react".

**Comment by janechu** [comment]
Consensus reached, the package will now be `fast-css-editor-react`, see the issue linked in the initial posting for further updates.
