### ISSUE TITLE
Heading jssStyles overwritten by Typography

### ISSUE THREAD

**Issue by brzho** [Microsoft/fast-dna#820]
In the render function:

```jsx
<Heading
   {...this.coerceRelatedTitleProps()}
   jssStyleSheet={titleStyles}
/>
```
Coercion function:
```jsx
private coerceRelatedTitleProps(): IHeadingHandledProps & IHeadingUnhandledProps {
     const coercedProps: Partial<IHeadingHandledProps & IHeadingUnhandledProps> = {
        level: HeadingLevel._6
    };

    return Object.assign({}, this.props.relatedStoriesTitle, coercedProps);
}
```

The style sheet:

```ts
export const titleStyles: Partial<ComponentStyles<IHeadingClassNameContract, IDesignSystem>> = {
    heading_6: {
        ...applyType("t7", "vp1"),
        fontWeight: `${fontWeight.normal}`
    }
};
```

The final styling takes the Typography styles over the Heading ones.

![capture](https://user-images.githubusercontent.com/40681678/44694997-a8f5e800-aa25-11e8-84ed-f42acd83901d.PNG)

DOM Element:

```html
<h3 class="typography_6-0-1-1568 heading_6-0-1-1562">Test</h3>
```

**Comment by chrisdholt** [comment]
Thanks @brzho, I think this is likely due to a couple of things. First, we are tracking an issue where styles are added after they are expected. There may be a work around for this. Secondly, this could be due to the styles being more specific due to media queries. The type ramp is responsive, so it could be that the media query just has more specificity. 

Regarding the specificity piece, one way that this might be able to be mitigated would be to turn this into a function instead of an object. I had an issue where that cropped up and that oddly helped me work around it. Perhaps it'll mitigate part of the issue for now. See below:

```
const styles: ComponentStyles<IHeadingClassNameContract, IDesignSystem> = (config: IDesignSystem): ComponentStyleSheet<IHeadingClassNameContract, IDesignSystem> => {
    return {
        heading: {
            ...applyType("t7", "vp1"),
            fontWeight: `${fontWeight.normal}`
        }
    };
};
```

+ @nicholasrice regarding potential specificity issues.
