### ISSUE TITLE
CodeClimate checks should run against any protected branch during PR

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#881]
Currently CodeClimate is only able to run against the master branch due to OSS licensing. This will create long term maintainability issues as we move to release branches. These checks (the checks currently run by CodeClimate on master) should be run on any protected branch that a pull request is being performed on.

Whether or not we use CodeClimate, this functionality is essential.

**Comment by awentzel** [comment]
After discussing with Code Climate (Noah Davis) and developers they are building a new feature for us to run our PR analysis for any open PRs (not just the ones against the default branch).  This may take 2-4 weeks.  But, will follow up as soon as we have a solution that works.  

Also, we agreed to perform Beta testing on this new feature since something is better than nothing for this feature.

**Comment by awentzel** [comment]
Email sent to Noah:
> "Wanted to follow up and see how this work is progressing?  Do you have anything for us to beta test > at this point?  When do you think this feature may be ready based on what you know today?"
<cite>@awentzel</cite>

**Comment by chrisdholt** [comment]
Has there been any additional feedback on this? As we look forward to our next major version it would be great to know if we should count on code climate providing insight on feature branches or not.

**Comment by chrisdholt** [comment]
Don't have enough context on this, but considering the ask is external and has been outstanding as a request for over a year, I'm closing this as obsolete.

**Comment by nickescobedo** [comment]
I've also been wanting this feature for a while. Unfortunate this hasn't been done.
