### ISSUE TITLE
Hypertext is not rendering with brand color in Edge

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#883]
when a href is set hypertext is not rendering with brand color in Edge.

**Comment by chrisdholt** [comment]
This seems to be an issue with the attribute selector we're using specifically in Edge. What's interesting is that I don't fully repro is in other environments using other technologies - super weird.

Suggest we try changing the selector to target something other than the href attribute. A quick an easy way to address this may be to use the `:link` and `:visited` pseduo selector to style the hypertext if it is actually a link.

So, instead of targeting `[href]` in JSS, we would have a style object that would look more like this:

```
const styles: ComponentStyles<HypertextClassNameContract, DesignSystem> = {
    hypertext: {
        outline: "none",
        textDecoration: "none",
        color: ensureForegroundNormal,
        // remove [href] attribute in favor of link and visited <======
        "&:link, &:visited": {
            ...applyHypertextBorder(1),
            color: ensureBrandNormal,
            "&:hover, &:focus": {
                ...applyHypertextBorder(2),
            },
        },
    },
};
```

**Comment by chrisdholt** [comment]
As a follow-up - `:any-link` would target both `:link` and `:visited` but is not widely supported and this  fix is needed in Edge.
