### ISSUE TITLE
can we make handledProps an abstract property?

### ISSUE THREAD

**Issue by prabashn** [Microsoft/fast-dna#926]
**What is your feature request? Please describe.**
New devs deriving from Foundation sometimes forget to implement handledProps. If we make this abstract folks will be forced to implement it. I would think omitting this property would essentially be a logical error no? Can we make this an abstract property?

**Describe the solution you'd like**
Convert the foundation to an abstract class with the abstract handledProps property so inheritors will be forced to return this.

**Describe alternatives you've considered**
Manually remembering to declare the handledProps property in the derived class. As new devs onboard however, this should be clearly pointed out (preferably b a compiler error, or else a new dev like me, will invariably go few hours (or a day) trying to figure out why React complains about "Warning: React does not recognize the `managedClasses` prop on a DOM element. ..."

**Additional context**
N/A

**Comment by nicholasrice** [comment]
I think this is a great idea.

**Comment by nicholasrice** [comment]
Yep, worst case it's an empty object. I think I'm okay with it, though I can see how folks might find it annoying if they're not using `unhandledProps`. I like the type safety though

**Comment by nicholasrice** [comment]
This would be breaking though - it would need to come in a major version bump

**Comment by prabashn** [comment]
Yeah, definitely. How many foundation dependent modules are there that can potentially break? Are there other folks using foundation stuff other than msnews? If so, this may end up being a bigger change I guess.

Another alternative is to create an abstract base to the existing base foundation so that new folks can inherit from that. Obviously not clean or unified, but maybe a good alternative if you don't want to make it a breaking change.

**Comment by chrisdholt** [comment]
@prabash, it would be all components and we can't really know who all is using Foundation. We do currently have a v3 release branch for components where we are doing breaking change work. We don't have an exact ETA on the v3 release, but it will include a good amount of breaking changes that have already gone in. I don't think we need to wait on the work, it's more a matter of when we deploy to npm.

**Comment by prabashn** [comment]
Awesome. If you have a future release branch, you can always put this in there if you think it makes sense. To me now that I've at least written one component, I know the pitfalls of doing this - but other new devs may not. Maybe it's just a matter of educating? Which I'm also ok with too. I'll let you guys decide the best course of action....

**Comment by chrisdholt** [comment]
@prabashn for sure, we would definitely put this in the release branch. As for education, we are currently working to improve that based on your feedback as well #941 :)

**Comment by nicholasrice** [comment]
@prabashn we've done the work to make the Foundation component an abstract class with this change: https://github.com/Microsoft/fast-dna/commit/5940dc2bc582c03db1d63121a7506f6d96d77e9c

Regarding making `handledProps` an abstract property:
After more consideration this isn't a change we want to implement. Selfishly, I would really like to do this for our own implementations because it ensures we've implemented this correctly ourselves and should result in fewer bugs over time. However, to make this change would require that *everyone* using Foundation to implement `handledProps` - *regardless* of if they're implement `unhandledProps` or not. For authors that don't opt into using `unhandledProps` this is pointless code and work. We want `fast-dna` to be a set of *reasonably* opinionated tools, and  unfortunately I think requiring implementations to assign this property runs counter to that.

If we can figure out an approach that accomplishes the best of both worlds then we'll be more than happy to implement that feature, but at this point I'm not sure what that would be.

**Comment by prabashn** [comment]
No problem. Thanks for giving thought into this. I think once devs start working with FAST components, they will get used to doing this :)
