### ISSUE TITLE
Some components do not implement prop interfaces correctly

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#947]
Certain components aren't implementing prop interfaces correctly, such as unhandledProp interfaces not being used. Ensure all interfaces are implemented correctly

**Comment by nicholasrice** [comment]
@chrisdholt how do you mean? What are you seeing that is incorrect?

**Comment by chrisdholt** [comment]
@nicholasrice I had seen several instances where we had `AllHTMLAttributes` instead of the *actual* element type. For instance, there are no alternate tags, the root element is simply `div` and should be typed as such. Perhaps some of these have already been corrected, but we should ensure that our typings represent the actual root element unless it requires an alternative solution (as button did with AllHTMLAttributes). My assumption when I saw this was that it was due to copy/paste and it got missed during code review.

**Comment by nicholasrice** [comment]
Cool, I'll write a separate issue for that.
